# Generated by Django 4.2.6 on 2023-10-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0002_remove_patient_user_patient_bio_patient_last_name_and_more"),
        ("prescription", "0002_remove_prescription_doctor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescription.prescription",
                    ),
                ),
            ],
        ),
    ]
