# Generated by Django 4.2.6 on 2023-10-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="rate",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="session_type",
            field=models.CharField(default="online", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[("p", "pending"), ("c", "completed")], default=1, max_length=1
            ),
            preserve_default=False,
        ),
    ]
