# Generated by Django 4.2.6 on 2023-10-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0002_remove_prescription_doctor_and_more"),
        ("session", "0002_session_description_session_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="prescription",
        ),
        migrations.AddField(
            model_name="session",
            name="prescription",
            field=models.ManyToManyField(to="prescription.prescription"),
        ),
    ]
