# Generated by Django 4.2.8 on 2024-01-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_system_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
    ]
