# Generated by Django 5.0.2 on 2024-02-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("injury", "0001_initial"),
        ("users", "0003_alter_patient_insurance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pateintdoctor",
            name="injury",
            field=models.ManyToManyField(blank=True, to="injury.injury"),
        ),
    ]
