# Generated by Django 4.2.6 on 2023-10-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("others", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("drugs", models.ManyToManyField(blank=True, to="prescription.drug")),
                (
                    "exercises",
                    models.ManyToManyField(blank=True, to="exercise.exercise"),
                ),
            ],
        ),
    ]
