# Generated by Django 4.2.6 on 2023-10-19 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient",
        ),
    ]
