# Generated by Django 4.2.6 on 2023-10-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0006_remove_doctor_is_active_remove_doctor_is_doctor"),
        ("exercise", "0002_alter_displacement_id_alter_displacement_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.doctor",
            ),
        ),
    ]
