# Generated by Django 4.2.6 on 2023-10-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=1
                    ),
                ),
                ("birth_date", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=10)),
                ("insurance_number", models.CharField(max_length=10)),
                ("insurance_company", models.CharField(max_length=100)),
                ("injury_date", models.DateField()),
                ("injury_description", models.CharField(max_length=100)),
                ("injury_type", models.CharField(max_length=100)),
                (
                    "medical_documents",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                ("password", models.CharField(max_length=100)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
                    ),
                ),
            ],
        ),
    ]
