# Generated by Django 4.2.6 on 2023-10-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_remove_patient_user_patient_bio_patient_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="password",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
