# Generated by Django 4.2.6 on 2023-10-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_remove_patient_password_patient_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_patient",
            field=models.BooleanField(default=True),
        ),
    ]
