# Generated by Django 4.2.6 on 2023-10-21 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0004_patient_password_patient_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="password",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="username",
        ),
    ]
