# Generated by Django 4.2.6 on 2023-10-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0005_remove_patient_password_remove_patient_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="is_doctor",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="is_patient",
        ),
        migrations.AddField(
            model_name="patient",
            name="username",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
