# Generated by Django 4.2.6 on 2023-10-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0006_remove_patient_is_active_remove_patient_is_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
