# Generated by Django 4.2.6 on 2023-10-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0007_patient_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="password",
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
