# Generated by Django 4.2.8 on 2024-01-13 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=11, unique=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Male"), ("f", "Female")], max_length=1
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "insurance_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "insurance_company",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("injury_date", models.DateField(blank=True, null=True)),
                (
                    "injury_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("injury_type", models.CharField(max_length=100)),
                (
                    "medical_documents",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                ("blood_type", models.CharField(blank=True, max_length=10, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="doctor.doctor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
