# Generated by Django 4.2.6 on 2023-10-19 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="last_name",
            field=models.CharField(default="Mohammadreza", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="name",
            field=models.CharField(default="amani", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
