# Generated by Django 4.2.6 on 2023-10-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0002_doctor_is_active_patient_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_doctor",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
