# Generated by Django 4.2.6 on 2023-10-20 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_doctor_is_doctor_patient_is_doctor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
