# Generated by Django 4.2.6 on 2023-10-21 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_doctor_email_doctor_password_doctor_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="is_doctor",
        ),
    ]
