# Generated by Django 4.2.6 on 2023-10-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0006_remove_doctor_is_active_remove_doctor_is_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
